### PR TITLE
Readme fixups

### PR DESCRIPTION
**Pull request by dokterbob**
Several readme fixups, making the code just a little bit more accesible for outside visitors.

### CODE REVIEW

**Comment by wvengen** [comment]
Thanks! I'm creating a separate branch for this. Plan is to rename rails3 to rails3-i18n, and use rails3 for non-i18n changes.

**Comment by dokterbob** [comment]
@wvengen I don't get what you mean. What does this have to do with i18n?

**Comment by wvengen** [comment]
I'd like to give upstream to easily merge back specific features - rails3 currently having only i18n-related changes. For other general changes that would contribute to upstream, a new branch is needed.

**Comment by fsmanuel** [comment]
done in the new repo. hope i got everything.

**Pull request closed without merging**
